### ISSUE TITLE
No CSS ? Where is this site deployed ? Please provide URL of deployed site

### ISSUE THREAD

**Issue by plusk-dev** [senMw/learn2020#2]
No CSS ? Where is this site deployed ? Please provide URL of deployed site

**Comment by aahnik** [comment]
Hi @YuvrajGeek , thanks for asking !!

**URL of Deployed Site:** https://senmw.github.io/learn2020

- I have not written any CSS.

- It is a simple site, which uses Tailblocks ( Tailwind CSS ) for only the home page. The rest of the pages have only a google sheet embedded on them

- This site is made for my mother, for sharing links of educational material to her school students. 

It is a simple site hosted on **GitHub Pages.**

Learn more about hosting on GitHub pages [here](https://pages.github.com/)

**Comment by senMw** [comment]
Repo name has been updated
URL https://senmw.github.io/learn2020/

**Comment by plusk-dev** [comment]
Okay, thanks!

**Comment by plusk-dev** [comment]
Isn't the site broken ? It always shows 404 not found

**Comment by aahnik** [comment]
No the site is not broken

just click on this  https://senmw.github.io/learn2020/

I checked just now ... it works fine

**Comment by aahnik** [comment]
The relative links have broken.. @YuvrajGeek 

Thanks for pointing out. The home page is loading, but other pages have broken, as I updated the repo name.

Will fix it soon

**Comment by senMw** [comment]
hi @YuvrajGeek the relative links have been fixed. Please check once again

Thanks a lot for informing..
